# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  bggext:
    image: bggext
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000 # Frontend
      - 5001:5001 # Backend
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-p", "5432"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 30s
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
