export { Dashboard } from "./Dashboard/Dashboard"
export { Login } from "./Login/Login"
export { Logout } from "./Logout/Logout"
export { Preferences } from "./Preferences/Preferences"
export { Register } from "./Register/Register"
